/**
 * Place profiles.
 *
 * Every index here is a coarse relative estimate, normalised so that the UK
 * national average is 1.0 for salary and cost. They are assembled from public
 * cost-of-living and salary surveys and are accurate enough to make a move
 * comparison meaningful and nowhere near accurate enough to be quoted. The UI
 * says so, and every one of them is editable.
 */

import type { LocationProfile } from './types';

export const LOCATIONS: LocationProfile[] = [
  {
    id: 'london',
    city: 'London',
    country: 'United Kingdom',
    currency: 'GBP',
    salaryIndex: 1.32,
    costIndex: 1.45,
    opportunityIndex: 88,
    socialFormationIndex: 62,
    lifeSatisfactionIndex: 68,
    commuteMinutes: 46,
    housingBurden: 0.42,
  },
  {
    id: 'manchester',
    city: 'Manchester',
    country: 'United Kingdom',
    currency: 'GBP',
    salaryIndex: 0.94,
    costIndex: 0.88,
    opportunityIndex: 62,
    socialFormationIndex: 72,
    lifeSatisfactionIndex: 72,
    commuteMinutes: 30,
    housingBurden: 0.28,
  },
  {
    id: 'edinburgh',
    city: 'Edinburgh',
    country: 'United Kingdom',
    currency: 'GBP',
    salaryIndex: 0.97,
    costIndex: 0.96,
    opportunityIndex: 58,
    socialFormationIndex: 70,
    lifeSatisfactionIndex: 75,
    commuteMinutes: 27,
    housingBurden: 0.31,
  },
  {
    id: 'bristol',
    city: 'Bristol',
    country: 'United Kingdom',
    currency: 'GBP',
    salaryIndex: 0.96,
    costIndex: 0.99,
    opportunityIndex: 57,
    socialFormationIndex: 71,
    lifeSatisfactionIndex: 74,
    commuteMinutes: 28,
    housingBurden: 0.33,
  },
  {
    id: 'uk-other',
    city: 'Elsewhere in the UK',
    country: 'United Kingdom',
    currency: 'GBP',
    salaryIndex: 0.88,
    costIndex: 0.84,
    opportunityIndex: 44,
    socialFormationIndex: 68,
    lifeSatisfactionIndex: 73,
    commuteMinutes: 25,
    housingBurden: 0.25,
  },
  {
    id: 'sf-bay',
    city: 'San Francisco Bay Area',
    country: 'United States',
    currency: 'USD',
    salaryIndex: 2.05,
    costIndex: 1.92,
    opportunityIndex: 96,
    socialFormationIndex: 55,
    lifeSatisfactionIndex: 64,
    commuteMinutes: 40,
    housingBurden: 0.48,
  },
  {
    id: 'nyc',
    city: 'New York City',
    country: 'United States',
    currency: 'USD',
    salaryIndex: 1.82,
    costIndex: 1.78,
    opportunityIndex: 93,
    socialFormationIndex: 58,
    lifeSatisfactionIndex: 63,
    commuteMinutes: 45,
    housingBurden: 0.47,
  },
  {
    id: 'seattle',
    city: 'Seattle',
    country: 'United States',
    currency: 'USD',
    salaryIndex: 1.74,
    costIndex: 1.48,
    opportunityIndex: 79,
    socialFormationIndex: 54,
    lifeSatisfactionIndex: 68,
    commuteMinutes: 33,
    housingBurden: 0.38,
  },
  {
    id: 'austin',
    city: 'Austin',
    country: 'United States',
    currency: 'USD',
    salaryIndex: 1.48,
    costIndex: 1.18,
    opportunityIndex: 70,
    socialFormationIndex: 68,
    lifeSatisfactionIndex: 70,
    commuteMinutes: 30,
    housingBurden: 0.32,
  },
  {
    id: 'berlin',
    city: 'Berlin',
    country: 'Germany',
    currency: 'EUR',
    salaryIndex: 0.98,
    costIndex: 0.98,
    opportunityIndex: 66,
    socialFormationIndex: 66,
    lifeSatisfactionIndex: 71,
    commuteMinutes: 34,
    housingBurden: 0.3,
  },
  {
    id: 'amsterdam',
    city: 'Amsterdam',
    country: 'Netherlands',
    currency: 'EUR',
    salaryIndex: 1.08,
    costIndex: 1.14,
    opportunityIndex: 68,
    socialFormationIndex: 64,
    lifeSatisfactionIndex: 78,
    commuteMinutes: 29,
    housingBurden: 0.34,
  },
  {
    id: 'lisbon',
    city: 'Lisbon',
    country: 'Portugal',
    currency: 'EUR',
    salaryIndex: 0.55,
    costIndex: 0.74,
    opportunityIndex: 47,
    socialFormationIndex: 70,
    lifeSatisfactionIndex: 70,
    commuteMinutes: 31,
    housingBurden: 0.36,
  },
  {
    id: 'dublin',
    city: 'Dublin',
    country: 'Ireland',
    currency: 'EUR',
    salaryIndex: 1.16,
    costIndex: 1.28,
    opportunityIndex: 65,
    socialFormationIndex: 66,
    lifeSatisfactionIndex: 71,
    commuteMinutes: 36,
    housingBurden: 0.4,
  },
  {
    id: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    currency: 'USD',
    salaryIndex: 1.24,
    costIndex: 1.36,
    opportunityIndex: 80,
    socialFormationIndex: 56,
    lifeSatisfactionIndex: 69,
    commuteMinutes: 38,
    housingBurden: 0.36,
  },
  {
    id: 'remote-low-cost',
    city: 'Remote, low cost of living',
    country: 'Anywhere',
    currency: 'GBP',
    salaryIndex: 1.0,
    costIndex: 0.62,
    opportunityIndex: 40,
    socialFormationIndex: 48,
    lifeSatisfactionIndex: 70,
    commuteMinutes: 0,
    housingBurden: 0.2,
  },
];

export const LOCATION_MAP: Record<string, LocationProfile> = Object.fromEntries(
  LOCATIONS.map((l) => [l.id, l]),
);

export function getLocation(id: string): LocationProfile {
  return LOCATION_MAP[id] ?? LOCATION_MAP['uk-other'];
}
